# Generated by Django 4.2.7 on 2023-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d')),
            ],
        ),
    ]
